### ISSUE TITLE
help for install

### ISSUE THREAD

**Issue by sandersonsoares** [kaycmendes/macOS-Catalina-for-Inspiron-5547#1]
Do you have any steps to install the hackintosh for this model with cataline? My notebook is the same, but I'm having trouble installing.

I boot the pendrive, but the screen hangs generally, if I had a step by step, it would be wonderful.

**Comment by kaycmendes** [comment]
Since you haven't told me your specs I'm going to give you two ways of booting it.

**First**,  if you have an outdated macbook or VM:
Just follow [this](https://www.tonymacx86.com/threads/unibeast-install-macos-catalina-on-any-supported-intel-based-pc.285366/) step-by-step

**Second**, if you're using windows: 

- Download this already bootable version of [Mojave](https://www.hackintoshzone.com/files/file/1069-niresh-mojave/)
- Download [transmac](https://transmac.en.uptodown.com/windows)
- Open transmac as administrator, insert your USB, right click it, select restore with disk image then finally select the Mojave image you dowloaded
- Make sure to set you BIOS boot mode UEFI
- Boot it and install it 
- Once Mojave is installed follow the [First](https://www.tonymacx86.com/threads/unibeast-install-macos-catalina-on-any-supported-intel-based-pc.285366/) step to install Catalina 

[Here's](https://www.tonymacx86.com/threads/guide-macos-sierra-10-12-2-on-dell-inspiron-5547.218629/) a couple of drivers/kext you're going to need after installing Mojave. The Pros of Mojave is that you can use Wifi.

Hope that helps.

**Comment by sandersonsoares** [comment]
Obrigado! Irei tentar, eu estava acompanhado alguns tutoriais no hackintosh brasil usando o etcher e uma imagem do catalina olarila. Sempre trava na hora do boot para instalação, rodei tudo e não consegui descobri o motivo. 

Essas são minhas especificações, acredito que é o mesmo modelo:
https://hackintoshbrasil.com/forum/topic/383-dell-inspiron-5547-compat%C3%ADvel-com-hackintosh/

Criei o issue em inglês, porque a princípio não tinha percebido que era do Brasil 😄

**Comment by kaycmendes** [comment]
Sim, mesmo modelo. Vou deixar o thread aberto caso tenha algum problema mas acho difícil sendo que tem os mesmos specs.

**Comment by sandersonsoares** [comment]
Na verdade, nem consegui fazer a instalação, tudo ocorreu bem sobre fazer a imagem no pendrive, e dar o boot por ele, mas quando seleciono a opção de instalar, ele fica num load infinito exibindo infinitas linhas de erro com:

```
Process[xxxx] crashed: Language Chooser. Too many corpses being created
```
Dando uma pesquisada pela internet vi que é um problema estranho referente a escolha do idioma da instalação, e muitos usuários recomendaram essa solução: 
https://www.hackintosh.computer/168/hackintosh-debug/#languagechooser

O problema é que infelizmente não resolveu pra mim, nem adicionando a flag `-s` na inicialização para fazer via comando, nem alterando o arquivo `config.plist`. Ainda o problema persiste. 

Já teve esse tipo de problema? Já tô sem idéia de como resolver, não sei se é alguma configuração da BIOS que não tá certa, já desabilitei os Virtualization e Virtualization I/O... Como provavelmente é a mesma máquina, o que você precisou desabilitar tanto na BIOS? 

Também já tentei restaurar o a imagem no pendrive novamente e mesmo assim o erro continua.

**Comment by kaycmendes** [comment]
Muda sua data na bios pra 24/9/2018 e tenta de novo.

**Comment by kaycmendes** [comment]
E pode deixar o Virtualization IO ativo

**Comment by sandersonsoares** [comment]
Infelizmente não funcionou, continuou dando o mesmo erro. Vi em alguns fóruns que apertando a tecla 6 pula o processo de escolha do idioma, ou `command + R`, mas nada aconteceu 😕.

**Comment by kaycmendes** [comment]
Não sei, porque instalei em ingles. Tenta em ingles pra ver se esse pode ser o problema.
Outra dica é tentar em diferentes entradas USB acho que a 3.0 é a da esquerda se não me engano.

**Comment by sandersonsoares** [comment]
Mas aí é que tá, não chega na tela de instalação, esse erro aparece antes de eu conseguir escolher um idioma. Eu instalaria em inglês sem problemas, mas não consigo chegar na tela de instalação. É durante o load de inicialização dela. 

Tentei em duas portas USB diferentes, na da esquerda e em uma da direita 😕

**Comment by kaycmendes** [comment]
Tenta com ele no modo legacy e confere se ta usando a ultima versão da [bios](https://www.dell.com/support/home/en-uk/product-support/product/inspiron-15-5547-laptop/drivers)
